### ISSUE TITLE
Unable to drag and drop file upload in version v0.16.0

### ISSUE THREAD

**Issue by uteminhduc** [pocketbase/pocketbase#2541]
After upgrading to version v0.16.0, it is no longer possible to drag and drop files. 
The file selection upload function still works normally.

**Comment by ganigeorgiev** [comment]
It works fine in Chrome but it doesn't work in Firefox. It is probably related to the changes from https://github.com/pocketbase/pocketbase/issues/2445.

I'll have a look at it sometime later today.

**Comment by ganigeorgiev** [comment]
There seems to be some slight implementation differences between the [dataTransfer.effectAllowed](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed) default value when dragging a file - for Chrome it is `copy`, for Firefox - `uninitialized` and for Gnome Web (uses older Safari's WebKit engine) is `copyMove`.

I've pushed a "fix" in `master` and it will be available sometime later today as part of v0.16.1.

**Comment by uteminhduc** [comment]
Sorry, missing browser information. 
I use the MS Edge 113.0.1774.50 (Official build) (64-bit).

**Comment by ganigeorgiev** [comment]
I don't have Edge to test it, but feel free to let me know if with the [v0.16.1 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.16.1) the issue still persists and I'll try to investigate it further (or implement a different approach).

**Comment by uteminhduc** [comment]
Still not working in version `0.16.1`
I also tried with Chrome v113.0.5672.127 (Official Build) (64-bit) but still not working.

**Comment by ganigeorgiev** [comment]
@uteminhduc I'm not able to reproduce it. For me it works fine on Chrome 111.0.5563.110, Firefox 111.0.1 and Gnome Web 41.0.

Note that if your file field is a single file upload and it already has a file we'll not allow uploading a new one.

I'll try to run an os update later to see if with newer browser versions it behave differently but I doubt that this is the case.

**Comment by ganigeorgiev** [comment]
I'm not sure why on Linux works fine but it seems that `dataTransfer.effectAllowed` is not reliable. I'll consider distinguishing the files drop and files sort differently.

**Comment by ganigeorgiev** [comment]
I tested v0.16.1 in a Windows 10 22H2 VM with Chrome 113 and it is working fine for me.
I'm not really sure what is the difference between my environment and yours (maybe a browser or file explorer plugin is interfering, different default browser settings, I'm not really sure...).

But to be on the safe side, since `dataTransfer.effectAllowed` default value doesn't seem consistent and reliable, I removed it and now the files drop should behave the same as in v0.15.3. I've pushed the fix in `master` and it will be available with the next v0.16.2 release sometime later this week.
